'''title'''
__title__ = 'musicnpp'
'''description'''
__description__ = 'A python traning dateset'
'''url'''
__url__ = 'https://github.com/WinHongLiu/musicnpp'
'''version'''
__version__ = '0.0.1'
'''author'''
__author__ = 'WinHong'
'''email'''
__email__ = '2518438125@qq.com'
'''license'''
__license__ = 'MIT License'
'''copyright'''
__copyright__ = 'Copyright 2022 WinHong'